name: flutter_undraw
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/KRTirtho/flutter_undraw

environment:
  sdk: ^3.7.0-209.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.2.2
  html: ^0.15.5
  slugify: ^2.0.0
  path: ^1.9.1
  change_case: ^2.2.0
  num_to_words: ^1.1.0

flutter:
  assets:
    - assets/undraw/