name: flutter_undraw
description: Undraw.co Illustrations for Flutter with customization options
version: 0.2.0+1
homepage: https://github.com/KRTirtho/flutter_undraw

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_lints: ^5.0.0
  http: ^1.2.2
  html: ^0.15.5
  slugify: ^2.0.0
  path: ^1.9.1
  change_case: ^2.2.0
  num_to_words: ^1.1.0
